
namespace Mobile_Shop_Database
{
    partial class Mobile
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Mobile));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.Label1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.idTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.brandTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.modeleTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.priceTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.stockTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.ramCB = new Guna.UI2.WinForms.Guna2ComboBox();
            this.romCB = new Guna.UI2.WinForms.Guna2ComboBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cameraTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Badd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Bupdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Bclear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Bdelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.mobileDGV = new Guna.UI2.WinForms.Guna2DataGridView();
            this.guna2PictureBox1 = new Guna.UI2.WinForms.Guna2PictureBox();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.mobileDGV)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // Label1
            // 
            this.Label1.AllowParentOverrides = false;
            this.Label1.AutoEllipsis = false;
            this.Label1.AutoSize = false;
            this.Label1.Cursor = System.Windows.Forms.Cursors.Default;
            this.Label1.CursorType = System.Windows.Forms.Cursors.Default;
            this.Label1.Font = new System.Drawing.Font("Century Gothic", 20.25F);
            this.Label1.ForeColor = System.Drawing.Color.DodgerBlue;
            this.Label1.Location = new System.Drawing.Point(293, 12);
            this.Label1.Name = "Label1";
            this.Label1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Label1.Size = new System.Drawing.Size(411, 35);
            this.Label1.TabIndex = 0;
            this.Label1.Text = "Mobile Management System\r\n";
            this.Label1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.Label1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 15F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel1.Location = new System.Drawing.Point(384, 53);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(233, 23);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Manage Mobiles\r\n";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.AutoSize = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 15F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel2.Location = new System.Drawing.Point(963, 12);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(25, 25);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "X";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel2.Click += new System.EventHandler(this.bunifuLabel2_Click);
            // 
            // idTB
            // 
            this.idTB.AcceptsReturn = false;
            this.idTB.AcceptsTab = false;
            this.idTB.AnimationSpeed = 200;
            this.idTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idTB.BackColor = System.Drawing.Color.White;
            this.idTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idTB.BackgroundImage")));
            this.idTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idTB.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.idTB.BorderRadius = 1;
            this.idTB.BorderThickness = 3;
            this.idTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idTB.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.idTB.DefaultText = "";
            this.idTB.FillColor = System.Drawing.Color.White;
            this.idTB.ForeColor = System.Drawing.Color.DeepPink;
            this.idTB.HideSelection = true;
            this.idTB.IconLeft = null;
            this.idTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idTB.IconPadding = 10;
            this.idTB.IconRight = null;
            this.idTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idTB.Lines = new string[0];
            this.idTB.Location = new System.Drawing.Point(75, 180);
            this.idTB.MaxLength = 32767;
            this.idTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.idTB.Modified = false;
            this.idTB.Multiline = false;
            this.idTB.Name = "idTB";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idTB.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idTB.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idTB.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.DeepPink;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idTB.OnIdleState = stateProperties4;
            this.idTB.Padding = new System.Windows.Forms.Padding(3);
            this.idTB.PasswordChar = '\0';
            this.idTB.PlaceholderForeColor = System.Drawing.Color.Gainsboro;
            this.idTB.PlaceholderText = "Enter ID ";
            this.idTB.ReadOnly = false;
            this.idTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idTB.SelectedText = "";
            this.idTB.SelectionLength = 0;
            this.idTB.SelectionStart = 0;
            this.idTB.ShortcutsEnabled = true;
            this.idTB.Size = new System.Drawing.Size(104, 52);
            this.idTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.idTB.TabIndex = 4;
            this.idTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.idTB.TextMarginBottom = 0;
            this.idTB.TextMarginLeft = 3;
            this.idTB.TextMarginTop = 0;
            this.idTB.TextPlaceholder = "Enter ID ";
            this.idTB.UseSystemPasswordChar = false;
            this.idTB.WordWrap = true;
            // 
            // brandTB
            // 
            this.brandTB.AcceptsReturn = false;
            this.brandTB.AcceptsTab = false;
            this.brandTB.AnimationSpeed = 200;
            this.brandTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.brandTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.brandTB.BackColor = System.Drawing.Color.White;
            this.brandTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("brandTB.BackgroundImage")));
            this.brandTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.brandTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.brandTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.brandTB.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.brandTB.BorderRadius = 1;
            this.brandTB.BorderThickness = 3;
            this.brandTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.brandTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.brandTB.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.brandTB.DefaultText = "";
            this.brandTB.FillColor = System.Drawing.Color.White;
            this.brandTB.ForeColor = System.Drawing.Color.DeepPink;
            this.brandTB.HideSelection = true;
            this.brandTB.IconLeft = null;
            this.brandTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.brandTB.IconPadding = 10;
            this.brandTB.IconRight = null;
            this.brandTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.brandTB.Lines = new string[0];
            this.brandTB.Location = new System.Drawing.Point(275, 180);
            this.brandTB.MaxLength = 32767;
            this.brandTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.brandTB.Modified = false;
            this.brandTB.Multiline = false;
            this.brandTB.Name = "brandTB";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.brandTB.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.brandTB.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.brandTB.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.DeepPink;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.brandTB.OnIdleState = stateProperties8;
            this.brandTB.Padding = new System.Windows.Forms.Padding(3);
            this.brandTB.PasswordChar = '\0';
            this.brandTB.PlaceholderForeColor = System.Drawing.Color.Gainsboro;
            this.brandTB.PlaceholderText = "Enter Brand";
            this.brandTB.ReadOnly = false;
            this.brandTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.brandTB.SelectedText = "";
            this.brandTB.SelectionLength = 0;
            this.brandTB.SelectionStart = 0;
            this.brandTB.ShortcutsEnabled = true;
            this.brandTB.Size = new System.Drawing.Size(168, 55);
            this.brandTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.brandTB.TabIndex = 6;
            this.brandTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.brandTB.TextMarginBottom = 0;
            this.brandTB.TextMarginLeft = 3;
            this.brandTB.TextMarginTop = 0;
            this.brandTB.TextPlaceholder = "Enter Brand";
            this.brandTB.UseSystemPasswordChar = false;
            this.brandTB.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.AutoSize = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel4.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel4.Location = new System.Drawing.Point(198, 188);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(92, 35);
            this.bunifuLabel4.TabIndex = 5;
            this.bunifuLabel4.Text = "Brand";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.AutoSize = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel3.Location = new System.Drawing.Point(19, 188);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(50, 35);
            this.bunifuLabel3.TabIndex = 7;
            this.bunifuLabel3.Text = "Id";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // modeleTB
            // 
            this.modeleTB.AcceptsReturn = false;
            this.modeleTB.AcceptsTab = false;
            this.modeleTB.AnimationSpeed = 200;
            this.modeleTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.modeleTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.modeleTB.BackColor = System.Drawing.Color.White;
            this.modeleTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modeleTB.BackgroundImage")));
            this.modeleTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.modeleTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modeleTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.modeleTB.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.modeleTB.BorderRadius = 1;
            this.modeleTB.BorderThickness = 3;
            this.modeleTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.modeleTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.modeleTB.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.modeleTB.DefaultText = "";
            this.modeleTB.FillColor = System.Drawing.Color.White;
            this.modeleTB.ForeColor = System.Drawing.Color.DeepPink;
            this.modeleTB.HideSelection = true;
            this.modeleTB.IconLeft = null;
            this.modeleTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.modeleTB.IconPadding = 10;
            this.modeleTB.IconRight = null;
            this.modeleTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.modeleTB.Lines = new string[0];
            this.modeleTB.Location = new System.Drawing.Point(555, 180);
            this.modeleTB.MaxLength = 32767;
            this.modeleTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.modeleTB.Modified = false;
            this.modeleTB.Multiline = false;
            this.modeleTB.Name = "modeleTB";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.modeleTB.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.modeleTB.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.modeleTB.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.DeepPink;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.modeleTB.OnIdleState = stateProperties12;
            this.modeleTB.Padding = new System.Windows.Forms.Padding(3);
            this.modeleTB.PasswordChar = '\0';
            this.modeleTB.PlaceholderForeColor = System.Drawing.Color.Gainsboro;
            this.modeleTB.PlaceholderText = "Enter Modele";
            this.modeleTB.ReadOnly = false;
            this.modeleTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.modeleTB.SelectedText = "";
            this.modeleTB.SelectionLength = 0;
            this.modeleTB.SelectionStart = 0;
            this.modeleTB.ShortcutsEnabled = true;
            this.modeleTB.Size = new System.Drawing.Size(177, 55);
            this.modeleTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.modeleTB.TabIndex = 9;
            this.modeleTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.modeleTB.TextMarginBottom = 0;
            this.modeleTB.TextMarginLeft = 3;
            this.modeleTB.TextMarginTop = 0;
            this.modeleTB.TextPlaceholder = "Enter Modele";
            this.modeleTB.UseSystemPasswordChar = false;
            this.modeleTB.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.AutoSize = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel5.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel5.Location = new System.Drawing.Point(462, 188);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(106, 35);
            this.bunifuLabel5.TabIndex = 8;
            this.bunifuLabel5.Text = "Modele";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // priceTB
            // 
            this.priceTB.AcceptsReturn = false;
            this.priceTB.AcceptsTab = false;
            this.priceTB.AnimationSpeed = 200;
            this.priceTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.priceTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.priceTB.BackColor = System.Drawing.Color.White;
            this.priceTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("priceTB.BackgroundImage")));
            this.priceTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.priceTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.priceTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.priceTB.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.priceTB.BorderRadius = 1;
            this.priceTB.BorderThickness = 3;
            this.priceTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.priceTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTB.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.priceTB.DefaultText = "";
            this.priceTB.FillColor = System.Drawing.Color.White;
            this.priceTB.ForeColor = System.Drawing.Color.DeepPink;
            this.priceTB.HideSelection = true;
            this.priceTB.IconLeft = null;
            this.priceTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTB.IconPadding = 10;
            this.priceTB.IconRight = null;
            this.priceTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTB.Lines = new string[0];
            this.priceTB.Location = new System.Drawing.Point(824, 180);
            this.priceTB.MaxLength = 32767;
            this.priceTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.priceTB.Modified = false;
            this.priceTB.Multiline = false;
            this.priceTB.Name = "priceTB";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTB.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.priceTB.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTB.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.DeepPink;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTB.OnIdleState = stateProperties16;
            this.priceTB.Padding = new System.Windows.Forms.Padding(3);
            this.priceTB.PasswordChar = '\0';
            this.priceTB.PlaceholderForeColor = System.Drawing.Color.Gainsboro;
            this.priceTB.PlaceholderText = "Enter Price";
            this.priceTB.ReadOnly = false;
            this.priceTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.priceTB.SelectedText = "";
            this.priceTB.SelectionLength = 0;
            this.priceTB.SelectionStart = 0;
            this.priceTB.ShortcutsEnabled = true;
            this.priceTB.Size = new System.Drawing.Size(134, 55);
            this.priceTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.priceTB.TabIndex = 11;
            this.priceTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.priceTB.TextMarginBottom = 0;
            this.priceTB.TextMarginLeft = 3;
            this.priceTB.TextMarginTop = 0;
            this.priceTB.TextPlaceholder = "Enter Price";
            this.priceTB.UseSystemPasswordChar = false;
            this.priceTB.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.AutoSize = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel6.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel6.Location = new System.Drawing.Point(747, 188);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(86, 35);
            this.bunifuLabel6.TabIndex = 10;
            this.bunifuLabel6.Text = "Price";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.AutoSize = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel7.Location = new System.Drawing.Point(84, 253);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(66, 35);
            this.bunifuLabel7.TabIndex = 13;
            this.bunifuLabel7.Text = "Stock";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // stockTB
            // 
            this.stockTB.AcceptsReturn = false;
            this.stockTB.AcceptsTab = false;
            this.stockTB.AnimationSpeed = 200;
            this.stockTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.stockTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.stockTB.BackColor = System.Drawing.Color.White;
            this.stockTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("stockTB.BackgroundImage")));
            this.stockTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.stockTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.stockTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.stockTB.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.stockTB.BorderRadius = 1;
            this.stockTB.BorderThickness = 3;
            this.stockTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.stockTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.stockTB.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.stockTB.DefaultText = "";
            this.stockTB.FillColor = System.Drawing.Color.White;
            this.stockTB.ForeColor = System.Drawing.Color.DeepPink;
            this.stockTB.HideSelection = true;
            this.stockTB.IconLeft = null;
            this.stockTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.stockTB.IconPadding = 10;
            this.stockTB.IconRight = null;
            this.stockTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.stockTB.Lines = new string[0];
            this.stockTB.Location = new System.Drawing.Point(156, 245);
            this.stockTB.MaxLength = 32767;
            this.stockTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.stockTB.Modified = false;
            this.stockTB.Multiline = false;
            this.stockTB.Name = "stockTB";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.stockTB.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.stockTB.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.stockTB.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.DeepPink;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.stockTB.OnIdleState = stateProperties20;
            this.stockTB.Padding = new System.Windows.Forms.Padding(3);
            this.stockTB.PasswordChar = '\0';
            this.stockTB.PlaceholderForeColor = System.Drawing.Color.Gainsboro;
            this.stockTB.PlaceholderText = "Enter Stock";
            this.stockTB.ReadOnly = false;
            this.stockTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.stockTB.SelectedText = "";
            this.stockTB.SelectionLength = 0;
            this.stockTB.SelectionStart = 0;
            this.stockTB.ShortcutsEnabled = true;
            this.stockTB.Size = new System.Drawing.Size(110, 55);
            this.stockTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.stockTB.TabIndex = 12;
            this.stockTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.stockTB.TextMarginBottom = 0;
            this.stockTB.TextMarginLeft = 3;
            this.stockTB.TextMarginTop = 0;
            this.stockTB.TextPlaceholder = "Enter Stock";
            this.stockTB.UseSystemPasswordChar = false;
            this.stockTB.WordWrap = true;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.AutoSize = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel8.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel8.Location = new System.Drawing.Point(310, 253);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(113, 35);
            this.bunifuLabel8.TabIndex = 14;
            this.bunifuLabel8.Text = "RAM in Gb";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ramCB
            // 
            this.ramCB.AutoRoundedCorners = true;
            this.ramCB.BackColor = System.Drawing.Color.Transparent;
            this.ramCB.BorderColor = System.Drawing.Color.DodgerBlue;
            this.ramCB.BorderRadius = 17;
            this.ramCB.BorderThickness = 2;
            this.ramCB.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.ramCB.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.ramCB.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.ramCB.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.ramCB.FocusedState.Parent = this.ramCB;
            this.ramCB.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ramCB.ForeColor = System.Drawing.Color.DeepPink;
            this.ramCB.HoverState.Parent = this.ramCB;
            this.ramCB.ItemHeight = 30;
            this.ramCB.Items.AddRange(new object[] {
            "1",
            "2",
            "4",
            "6",
            "8",
            "10",
            "12"});
            this.ramCB.ItemsAppearance.Parent = this.ramCB;
            this.ramCB.Location = new System.Drawing.Point(429, 253);
            this.ramCB.Name = "ramCB";
            this.ramCB.ShadowDecoration.Parent = this.ramCB;
            this.ramCB.Size = new System.Drawing.Size(165, 36);
            this.ramCB.TabIndex = 15;
            // 
            // romCB
            // 
            this.romCB.AutoRoundedCorners = true;
            this.romCB.BackColor = System.Drawing.Color.Transparent;
            this.romCB.BorderColor = System.Drawing.Color.DodgerBlue;
            this.romCB.BorderRadius = 17;
            this.romCB.BorderThickness = 2;
            this.romCB.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.romCB.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.romCB.FocusedColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.romCB.FocusedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.romCB.FocusedState.Parent = this.romCB;
            this.romCB.Font = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.romCB.ForeColor = System.Drawing.Color.DeepPink;
            this.romCB.HoverState.Parent = this.romCB;
            this.romCB.ItemHeight = 30;
            this.romCB.Items.AddRange(new object[] {
            "16",
            "32",
            "64",
            "128",
            "256"});
            this.romCB.ItemsAppearance.Parent = this.romCB;
            this.romCB.Location = new System.Drawing.Point(754, 253);
            this.romCB.Name = "romCB";
            this.romCB.ShadowDecoration.Parent = this.romCB;
            this.romCB.Size = new System.Drawing.Size(165, 36);
            this.romCB.TabIndex = 17;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.AutoSize = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel9.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel9.Location = new System.Drawing.Point(635, 253);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(113, 35);
            this.bunifuLabel9.TabIndex = 16;
            this.bunifuLabel9.Text = "ROM in Gb";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cameraTB
            // 
            this.cameraTB.AcceptsReturn = false;
            this.cameraTB.AcceptsTab = false;
            this.cameraTB.AnimationSpeed = 200;
            this.cameraTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cameraTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cameraTB.BackColor = System.Drawing.Color.White;
            this.cameraTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cameraTB.BackgroundImage")));
            this.cameraTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cameraTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cameraTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cameraTB.BorderColorIdle = System.Drawing.Color.DodgerBlue;
            this.cameraTB.BorderRadius = 1;
            this.cameraTB.BorderThickness = 3;
            this.cameraTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cameraTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cameraTB.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cameraTB.DefaultText = "";
            this.cameraTB.FillColor = System.Drawing.Color.White;
            this.cameraTB.ForeColor = System.Drawing.Color.DeepPink;
            this.cameraTB.HideSelection = true;
            this.cameraTB.IconLeft = null;
            this.cameraTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cameraTB.IconPadding = 10;
            this.cameraTB.IconRight = null;
            this.cameraTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cameraTB.Lines = new string[0];
            this.cameraTB.Location = new System.Drawing.Point(453, 304);
            this.cameraTB.MaxLength = 32767;
            this.cameraTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.cameraTB.Modified = false;
            this.cameraTB.Multiline = false;
            this.cameraTB.Name = "cameraTB";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cameraTB.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cameraTB.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cameraTB.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.DeepPink;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cameraTB.OnIdleState = stateProperties24;
            this.cameraTB.Padding = new System.Windows.Forms.Padding(3);
            this.cameraTB.PasswordChar = '\0';
            this.cameraTB.PlaceholderForeColor = System.Drawing.Color.Gainsboro;
            this.cameraTB.PlaceholderText = "Enter Camera in MP";
            this.cameraTB.ReadOnly = false;
            this.cameraTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cameraTB.SelectedText = "";
            this.cameraTB.SelectionLength = 0;
            this.cameraTB.SelectionStart = 0;
            this.cameraTB.ShortcutsEnabled = true;
            this.cameraTB.Size = new System.Drawing.Size(183, 55);
            this.cameraTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.cameraTB.TabIndex = 19;
            this.cameraTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.cameraTB.TextMarginBottom = 0;
            this.cameraTB.TextMarginLeft = 3;
            this.cameraTB.TextMarginTop = 0;
            this.cameraTB.TextPlaceholder = "Enter Camera in MP";
            this.cameraTB.UseSystemPasswordChar = false;
            this.cameraTB.WordWrap = true;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.AutoSize = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel10.ForeColor = System.Drawing.Color.DeepPink;
            this.bunifuLabel10.Location = new System.Drawing.Point(302, 321);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(145, 35);
            this.bunifuLabel10.TabIndex = 18;
            this.bunifuLabel10.Text = "Camera in MP";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.DeepPink;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel11);
            this.bunifuPanel1.Location = new System.Drawing.Point(-10, 439);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1023, 34);
            this.bunifuPanel1.TabIndex = 20;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.AutoSize = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Century Gothic", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel11.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel11.Location = new System.Drawing.Point(407, 3);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(194, 30);
            this.bunifuLabel11.TabIndex = 21;
            this.bunifuLabel11.Text = "Mobile Stock";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Badd
            // 
            this.Badd.AllowAnimations = true;
            this.Badd.AllowMouseEffects = true;
            this.Badd.AllowToggling = false;
            this.Badd.AnimationSpeed = 200;
            this.Badd.AutoGenerateColors = false;
            this.Badd.AutoRoundBorders = true;
            this.Badd.AutoSizeLeftIcon = true;
            this.Badd.AutoSizeRightIcon = true;
            this.Badd.BackColor = System.Drawing.Color.Transparent;
            this.Badd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Badd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Badd.BackgroundImage")));
            this.Badd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Badd.ButtonText = "Add";
            this.Badd.ButtonTextMarginLeft = 0;
            this.Badd.ColorContrastOnClick = 45;
            this.Badd.ColorContrastOnHover = 45;
            this.Badd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.Badd.CustomizableEdges = borderEdges1;
            this.Badd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Badd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Badd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Badd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Badd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Badd.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Badd.ForeColor = System.Drawing.Color.White;
            this.Badd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Badd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Badd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Badd.IconMarginLeft = 11;
            this.Badd.IconPadding = 10;
            this.Badd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Badd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Badd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Badd.IconSize = 25;
            this.Badd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Badd.IdleBorderRadius = 29;
            this.Badd.IdleBorderThickness = 1;
            this.Badd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Badd.IdleIconLeftImage = null;
            this.Badd.IdleIconRightImage = null;
            this.Badd.IndicateFocus = true;
            this.Badd.Location = new System.Drawing.Point(193, 390);
            this.Badd.Name = "Badd";
            this.Badd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Badd.OnDisabledState.BorderRadius = 1;
            this.Badd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Badd.OnDisabledState.BorderThickness = 1;
            this.Badd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Badd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Badd.OnDisabledState.IconLeftImage = null;
            this.Badd.OnDisabledState.IconRightImage = null;
            this.Badd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Badd.onHoverState.BorderRadius = 1;
            this.Badd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Badd.onHoverState.BorderThickness = 1;
            this.Badd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Badd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Badd.onHoverState.IconLeftImage = null;
            this.Badd.onHoverState.IconRightImage = null;
            this.Badd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Badd.OnIdleState.BorderRadius = 1;
            this.Badd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Badd.OnIdleState.BorderThickness = 1;
            this.Badd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Badd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Badd.OnIdleState.IconLeftImage = null;
            this.Badd.OnIdleState.IconRightImage = null;
            this.Badd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Badd.OnPressedState.BorderRadius = 1;
            this.Badd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Badd.OnPressedState.BorderThickness = 1;
            this.Badd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Badd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Badd.OnPressedState.IconLeftImage = null;
            this.Badd.OnPressedState.IconRightImage = null;
            this.Badd.Size = new System.Drawing.Size(127, 31);
            this.Badd.TabIndex = 21;
            this.Badd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Badd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Badd.TextMarginLeft = 0;
            this.Badd.TextPadding = new System.Windows.Forms.Padding(0);
            this.Badd.UseDefaultRadiusAndThickness = true;
            this.Badd.Click += new System.EventHandler(this.Badd_Click);
            // 
            // Bupdate
            // 
            this.Bupdate.AllowAnimations = true;
            this.Bupdate.AllowMouseEffects = true;
            this.Bupdate.AllowToggling = false;
            this.Bupdate.AnimationSpeed = 200;
            this.Bupdate.AutoGenerateColors = false;
            this.Bupdate.AutoRoundBorders = true;
            this.Bupdate.AutoSizeLeftIcon = true;
            this.Bupdate.AutoSizeRightIcon = true;
            this.Bupdate.BackColor = System.Drawing.Color.Transparent;
            this.Bupdate.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Bupdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Bupdate.BackgroundImage")));
            this.Bupdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bupdate.ButtonText = "Update";
            this.Bupdate.ButtonTextMarginLeft = 0;
            this.Bupdate.ColorContrastOnClick = 45;
            this.Bupdate.ColorContrastOnHover = 45;
            this.Bupdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Bupdate.CustomizableEdges = borderEdges2;
            this.Bupdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Bupdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bupdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bupdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bupdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Bupdate.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Bupdate.ForeColor = System.Drawing.Color.White;
            this.Bupdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Bupdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Bupdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Bupdate.IconMarginLeft = 11;
            this.Bupdate.IconPadding = 10;
            this.Bupdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Bupdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Bupdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Bupdate.IconSize = 25;
            this.Bupdate.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Bupdate.IdleBorderRadius = 29;
            this.Bupdate.IdleBorderThickness = 1;
            this.Bupdate.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Bupdate.IdleIconLeftImage = null;
            this.Bupdate.IdleIconRightImage = null;
            this.Bupdate.IndicateFocus = true;
            this.Bupdate.Location = new System.Drawing.Point(356, 390);
            this.Bupdate.Name = "Bupdate";
            this.Bupdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bupdate.OnDisabledState.BorderRadius = 1;
            this.Bupdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bupdate.OnDisabledState.BorderThickness = 1;
            this.Bupdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bupdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bupdate.OnDisabledState.IconLeftImage = null;
            this.Bupdate.OnDisabledState.IconRightImage = null;
            this.Bupdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Bupdate.onHoverState.BorderRadius = 1;
            this.Bupdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bupdate.onHoverState.BorderThickness = 1;
            this.Bupdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Bupdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Bupdate.onHoverState.IconLeftImage = null;
            this.Bupdate.onHoverState.IconRightImage = null;
            this.Bupdate.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Bupdate.OnIdleState.BorderRadius = 1;
            this.Bupdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bupdate.OnIdleState.BorderThickness = 1;
            this.Bupdate.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Bupdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Bupdate.OnIdleState.IconLeftImage = null;
            this.Bupdate.OnIdleState.IconRightImage = null;
            this.Bupdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bupdate.OnPressedState.BorderRadius = 1;
            this.Bupdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bupdate.OnPressedState.BorderThickness = 1;
            this.Bupdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bupdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Bupdate.OnPressedState.IconLeftImage = null;
            this.Bupdate.OnPressedState.IconRightImage = null;
            this.Bupdate.Size = new System.Drawing.Size(127, 31);
            this.Bupdate.TabIndex = 22;
            this.Bupdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Bupdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Bupdate.TextMarginLeft = 0;
            this.Bupdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.Bupdate.UseDefaultRadiusAndThickness = true;
            this.Bupdate.Click += new System.EventHandler(this.Bupdate_Click);
            // 
            // Bclear
            // 
            this.Bclear.AllowAnimations = true;
            this.Bclear.AllowMouseEffects = true;
            this.Bclear.AllowToggling = false;
            this.Bclear.AnimationSpeed = 200;
            this.Bclear.AutoGenerateColors = false;
            this.Bclear.AutoRoundBorders = true;
            this.Bclear.AutoSizeLeftIcon = true;
            this.Bclear.AutoSizeRightIcon = true;
            this.Bclear.BackColor = System.Drawing.Color.Transparent;
            this.Bclear.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Bclear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Bclear.BackgroundImage")));
            this.Bclear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bclear.ButtonText = "Clear";
            this.Bclear.ButtonTextMarginLeft = 0;
            this.Bclear.ColorContrastOnClick = 45;
            this.Bclear.ColorContrastOnHover = 45;
            this.Bclear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.Bclear.CustomizableEdges = borderEdges3;
            this.Bclear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Bclear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bclear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bclear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bclear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Bclear.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Bclear.ForeColor = System.Drawing.Color.White;
            this.Bclear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Bclear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Bclear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Bclear.IconMarginLeft = 11;
            this.Bclear.IconPadding = 10;
            this.Bclear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Bclear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Bclear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Bclear.IconSize = 25;
            this.Bclear.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Bclear.IdleBorderRadius = 29;
            this.Bclear.IdleBorderThickness = 1;
            this.Bclear.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Bclear.IdleIconLeftImage = null;
            this.Bclear.IdleIconRightImage = null;
            this.Bclear.IndicateFocus = true;
            this.Bclear.Location = new System.Drawing.Point(681, 390);
            this.Bclear.Name = "Bclear";
            this.Bclear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bclear.OnDisabledState.BorderRadius = 1;
            this.Bclear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bclear.OnDisabledState.BorderThickness = 1;
            this.Bclear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bclear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bclear.OnDisabledState.IconLeftImage = null;
            this.Bclear.OnDisabledState.IconRightImage = null;
            this.Bclear.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Bclear.onHoverState.BorderRadius = 1;
            this.Bclear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bclear.onHoverState.BorderThickness = 1;
            this.Bclear.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Bclear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Bclear.onHoverState.IconLeftImage = null;
            this.Bclear.onHoverState.IconRightImage = null;
            this.Bclear.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Bclear.OnIdleState.BorderRadius = 1;
            this.Bclear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bclear.OnIdleState.BorderThickness = 1;
            this.Bclear.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Bclear.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Bclear.OnIdleState.IconLeftImage = null;
            this.Bclear.OnIdleState.IconRightImage = null;
            this.Bclear.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bclear.OnPressedState.BorderRadius = 1;
            this.Bclear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bclear.OnPressedState.BorderThickness = 1;
            this.Bclear.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bclear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Bclear.OnPressedState.IconLeftImage = null;
            this.Bclear.OnPressedState.IconRightImage = null;
            this.Bclear.Size = new System.Drawing.Size(127, 31);
            this.Bclear.TabIndex = 24;
            this.Bclear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Bclear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Bclear.TextMarginLeft = 0;
            this.Bclear.TextPadding = new System.Windows.Forms.Padding(0);
            this.Bclear.UseDefaultRadiusAndThickness = true;
            this.Bclear.Click += new System.EventHandler(this.Bclear_Click);
            // 
            // Bdelete
            // 
            this.Bdelete.AllowAnimations = true;
            this.Bdelete.AllowMouseEffects = true;
            this.Bdelete.AllowToggling = false;
            this.Bdelete.AnimationSpeed = 200;
            this.Bdelete.AutoGenerateColors = false;
            this.Bdelete.AutoRoundBorders = true;
            this.Bdelete.AutoSizeLeftIcon = true;
            this.Bdelete.AutoSizeRightIcon = true;
            this.Bdelete.BackColor = System.Drawing.Color.Transparent;
            this.Bdelete.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Bdelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Bdelete.BackgroundImage")));
            this.Bdelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bdelete.ButtonText = "Delete";
            this.Bdelete.ButtonTextMarginLeft = 0;
            this.Bdelete.ColorContrastOnClick = 45;
            this.Bdelete.ColorContrastOnHover = 45;
            this.Bdelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Bdelete.CustomizableEdges = borderEdges4;
            this.Bdelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Bdelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bdelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bdelete.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bdelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Bdelete.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Bdelete.ForeColor = System.Drawing.Color.White;
            this.Bdelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Bdelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Bdelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Bdelete.IconMarginLeft = 11;
            this.Bdelete.IconPadding = 10;
            this.Bdelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Bdelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Bdelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Bdelete.IconSize = 25;
            this.Bdelete.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Bdelete.IdleBorderRadius = 29;
            this.Bdelete.IdleBorderThickness = 1;
            this.Bdelete.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Bdelete.IdleIconLeftImage = null;
            this.Bdelete.IdleIconRightImage = null;
            this.Bdelete.IndicateFocus = true;
            this.Bdelete.Location = new System.Drawing.Point(518, 390);
            this.Bdelete.Name = "Bdelete";
            this.Bdelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Bdelete.OnDisabledState.BorderRadius = 1;
            this.Bdelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bdelete.OnDisabledState.BorderThickness = 1;
            this.Bdelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Bdelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Bdelete.OnDisabledState.IconLeftImage = null;
            this.Bdelete.OnDisabledState.IconRightImage = null;
            this.Bdelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Bdelete.onHoverState.BorderRadius = 1;
            this.Bdelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bdelete.onHoverState.BorderThickness = 1;
            this.Bdelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Bdelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Bdelete.onHoverState.IconLeftImage = null;
            this.Bdelete.onHoverState.IconRightImage = null;
            this.Bdelete.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Bdelete.OnIdleState.BorderRadius = 1;
            this.Bdelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bdelete.OnIdleState.BorderThickness = 1;
            this.Bdelete.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Bdelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Bdelete.OnIdleState.IconLeftImage = null;
            this.Bdelete.OnIdleState.IconRightImage = null;
            this.Bdelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bdelete.OnPressedState.BorderRadius = 1;
            this.Bdelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Bdelete.OnPressedState.BorderThickness = 1;
            this.Bdelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Bdelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Bdelete.OnPressedState.IconLeftImage = null;
            this.Bdelete.OnPressedState.IconRightImage = null;
            this.Bdelete.Size = new System.Drawing.Size(127, 31);
            this.Bdelete.TabIndex = 23;
            this.Bdelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Bdelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Bdelete.TextMarginLeft = 0;
            this.Bdelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.Bdelete.UseDefaultRadiusAndThickness = true;
            this.Bdelete.Click += new System.EventHandler(this.Bdelete_Click);
            // 
            // mobileDGV
            // 
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.Highlight;
            this.mobileDGV.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.mobileDGV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.mobileDGV.BackgroundColor = System.Drawing.Color.White;
            this.mobileDGV.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.mobileDGV.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.mobileDGV.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.mobileDGV.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.mobileDGV.ColumnHeadersHeight = 25;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.mobileDGV.DefaultCellStyle = dataGridViewCellStyle3;
            this.mobileDGV.EnableHeadersVisualStyles = false;
            this.mobileDGV.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.mobileDGV.Location = new System.Drawing.Point(5, 479);
            this.mobileDGV.Name = "mobileDGV";
            this.mobileDGV.RowHeadersVisible = false;
            this.mobileDGV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.mobileDGV.Size = new System.Drawing.Size(992, 203);
            this.mobileDGV.TabIndex = 25;
            this.mobileDGV.ThemeStyle.AlternatingRowsStyle.BackColor = System.Drawing.SystemColors.Highlight;
            this.mobileDGV.ThemeStyle.AlternatingRowsStyle.Font = null;
            this.mobileDGV.ThemeStyle.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Empty;
            this.mobileDGV.ThemeStyle.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.mobileDGV.ThemeStyle.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Empty;
            this.mobileDGV.ThemeStyle.BackColor = System.Drawing.Color.White;
            this.mobileDGV.ThemeStyle.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(229)))), ((int)(((byte)(255)))));
            this.mobileDGV.ThemeStyle.HeaderStyle.BackColor = System.Drawing.SystemColors.Highlight;
            this.mobileDGV.ThemeStyle.HeaderStyle.BorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            this.mobileDGV.ThemeStyle.HeaderStyle.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.mobileDGV.ThemeStyle.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.mobileDGV.ThemeStyle.HeaderStyle.HeaightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.EnableResizing;
            this.mobileDGV.ThemeStyle.HeaderStyle.Height = 25;
            this.mobileDGV.ThemeStyle.ReadOnly = false;
            this.mobileDGV.ThemeStyle.RowsStyle.BackColor = System.Drawing.Color.White;
            this.mobileDGV.ThemeStyle.RowsStyle.BorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.mobileDGV.ThemeStyle.RowsStyle.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.mobileDGV.ThemeStyle.RowsStyle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.mobileDGV.ThemeStyle.RowsStyle.Height = 22;
            this.mobileDGV.ThemeStyle.RowsStyle.SelectionBackColor = System.Drawing.Color.Empty;
            this.mobileDGV.ThemeStyle.RowsStyle.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(69)))), ((int)(((byte)(94)))));
            this.mobileDGV.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.mobileDGV_CellContentClick);
            // 
            // guna2PictureBox1
            // 
            this.guna2PictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("guna2PictureBox1.Image")));
            this.guna2PictureBox1.ImageRotate = 0F;
            this.guna2PictureBox1.Location = new System.Drawing.Point(462, 82);
            this.guna2PictureBox1.Name = "guna2PictureBox1";
            this.guna2PictureBox1.ShadowDecoration.Parent = this.guna2PictureBox1;
            this.guna2PictureBox1.Size = new System.Drawing.Size(64, 64);
            this.guna2PictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.guna2PictureBox1.TabIndex = 26;
            this.guna2PictureBox1.TabStop = false;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = true;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.DeepPink;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Back";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges5;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.DeepPink;
            this.bunifuButton1.IdleBorderRadius = 33;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.DeepPink;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = true;
            this.bunifuButton1.Location = new System.Drawing.Point(453, 688);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DeepPink;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DeepPink;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(94, 35);
            this.bunifuButton1.TabIndex = 27;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // Mobile
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1000, 726);
            this.Controls.Add(this.bunifuButton1);
            this.Controls.Add(this.guna2PictureBox1);
            this.Controls.Add(this.mobileDGV);
            this.Controls.Add(this.Bclear);
            this.Controls.Add(this.Bdelete);
            this.Controls.Add(this.Bupdate);
            this.Controls.Add(this.Badd);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.cameraTB);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.romCB);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.ramCB);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.stockTB);
            this.Controls.Add(this.priceTB);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.modeleTB);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.brandTB);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.idTB);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.Label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Mobile";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Mobile";
            this.Load += new System.EventHandler(this.Mobile_Load);
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.mobileDGV)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.guna2PictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuLabel Label1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox idTB;
        private Bunifu.UI.WinForms.BunifuTextBox brandTB;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuTextBox modeleTB;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox priceTB;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuTextBox stockTB;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Guna.UI2.WinForms.Guna2ComboBox ramCB;
        private Guna.UI2.WinForms.Guna2ComboBox romCB;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox cameraTB;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Badd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Bupdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Bclear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Bdelete;
        private Guna.UI2.WinForms.Guna2DataGridView mobileDGV;
        private Guna.UI2.WinForms.Guna2PictureBox guna2PictureBox1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
    }
}